### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by jsmits21** [MrSwitch/node-oauth-shim#13]
Let me first say that I'm new to node, and I'm even greener when it comes to CORS stuff. I've enabled cors on my server using the cors npm package. The options request succeeds but the post returns a gateway timeout. 

Is there something I need to configure with the shim to allow CORS requests yet?

Your service works great, and I trust you with the app secrets, but I'm not too sure my team will feel the same so I'd rather get this service up and running on my end.

Given that you record a server url with your service, I'm assuming that this needs to be passed to the oauthshim? Or do I need hello.js to attach a header when sending the requests?

**Comment by jsmits21** [comment]
![image](https://cloud.githubusercontent.com/assets/954812/7097523/df8a4b84-df9b-11e4-82a8-e12f7d1e2841.png)

**Comment by MrSwitch** [comment]
@jsmits21 that's very odd, its getting through the preflight step of CORS (returning an OPTIONS header) 

You dont need `cors` package - the library handles these.

If you want a point of reference, have you inspected the implementation for the //auth-server https://github.com/MrSwitch/auth-server/blob/master/app.js#L248 yet?

**Comment by MrSwitch** [comment]
inactive
