### ISSUE TITLE
Vimeo requires extra Authorization header on /access_token

### ISSUE THREAD

**Issue by jimmed** [MrSwitch/node-oauth-shim#14]
I've been using hello.js with node-oauth-shim for some months now, and recently decided to add Vimeo OAuth support to my app.

Using node-oauth-shim, simply using my client ID + secret is not sufficient to get a successful response from Vimeo's `/access_token` endpoint, [as an additional header is required][1]:

> The authorization header can be found on your app page or can be built with your client id and client secret
> ```'Authorization: basic ' + base64(client_id + ':' + client_secret)```

I'm happy to implement a workaround, but I'd rather not hard-code a check for `network === 'vimeo'`. What is the best way of making this configurable?

[1]: https://developer.vimeo.com/api/authentication#generate-redirect

**Comment by MrSwitch** [comment]
This has been included and deployed to //auth-server and you can test this out here http://adodson.com/hello.js/demos/vimeo.html
