### ISSUE TITLE
Version 1.0a not including oauth_callback from preflight request

### ISSUE THREAD

**Issue by coderkevin** [MrSwitch/node-oauth-shim#16]
I was trying out a Version 1.0a service and the oauth_callback wasn't being set, so it wasn't redirecting back to my application after authentication/authorization. While digging in the code, I came across this:

In oauth1.js, at line 212:
```
// Version 1.0a requires the oauth_callback parameter for signing the request
if( version !== '1.0a' ){
	// Define the OAUTH CALLBACK Parameters
	params.oauth_callback = oauth_callback;
}
```

From the comments above and below, it seems to me that this should be ``` if( version === '1.0a' ){``` instead. So I changed it locally and my redirect started working. So it seems to me that this should be the way, unless I'm mistaken somewhere.

**Comment by MrSwitch** [comment]
The changes in OAuth 1.0a removed the oauth_callback from this redirection step (see step no. 3 http://wiki.oauth.net/w/page/12238555/Signed%20Callback%20URLs). However i see that this should be omitted if the response.oauth_callback_confirmed=true, rather than if version !== '1.0a' (which i realize is also rather misleading, and should be written version.toString() === '1' anyway)

Does my changes fed9730 fix your issues with your OAuth 1.0a endpoint?

**Comment by coderkevin** [comment]
I'll check this out in the next day or two and get back to you. Thanks for the quick response!

**Comment by coderkevin** [comment]
Turns out that the server code wasn't storing the callback and associating it with the request to recall it after authorization, even though the server code was setting oauth_callback_confirmed = true. After fixing the server code to store the callback between the request and authorize calls it works. However, it also works with the existing ```version !== '1.0a'``` check as well.

So, given that the server code I'm using was originally designed to send oauth_callback_confirmed, I can't really verify if your change fixes anything, since it doesn't apply to my situation anymore. Sorry!

P.S. I'm working on a module that will add support to any WordPress site via the WP-API/OAuth1 plugin (https://github.com/WP-API/OAuth1) and the v2 WP API. I will be putting up a PR for that sometime in the next few weeks. It will have to work just a little differently than the other modules though, since each WordPress site will have a different URL, Client ID, and Secret.

**Comment by MrSwitch** [comment]
Awesome, please bring me in on that conversation.
